# Generated by Django 2.1.7 on 2020-12-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=25)),
            ],
        ),
    ]
