# Generated by Django 2.1.7 on 2020-12-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='details',
        ),
    ]
