# Generated by Django 2.1.7 on 2020-12-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0003_auto_20201229_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
