# Generated by Django 2.1.7 on 2020-12-29 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0004_auto_20201229_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='last_name',
        ),
    ]
