# Generated by Django 2.1.7 on 2020-12-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0005_auto_20201229_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='image',
            field=models.BinaryField(blank=True),
        ),
    ]
